CREATE TABLE IF NOT EXISTS banks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    name_ko TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS policy_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id INTEGER NOT NULL REFERENCES banks(id),
    policy_key TEXT NOT NULL,
    label_ko TEXT NOT NULL,
    customer_type TEXT NOT NULL,
    account_type TEXT NOT NULL,
    version INTEGER NOT NULL CHECK (version > 0),
    status TEXT NOT NULL CHECK (status IN ('draft', 'published', 'retired')),
    verified_at DATE NOT NULL,
    notes TEXT,
    UNIQUE (bank_id, policy_key, version)
);

CREATE TABLE IF NOT EXISTS sources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_version_id INTEGER NOT NULL
        REFERENCES policy_versions(id) ON DELETE CASCADE,
    source_key TEXT NOT NULL,
    scope TEXT NOT NULL,
    publisher TEXT NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    checked_at DATE NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (policy_version_id, source_key)
);

CREATE TABLE IF NOT EXISTS policy_operations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_version_id INTEGER NOT NULL
        REFERENCES policy_versions(id) ON DELETE CASCADE,
    operation_code TEXT NOT NULL,
    label_ko TEXT NOT NULL,
    notes TEXT,
    UNIQUE (policy_version_id, operation_code)
);

CREATE TABLE IF NOT EXISTS requirement_sets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_version_id INTEGER NOT NULL
        REFERENCES policy_versions(id) ON DELETE CASCADE,
    source_id INTEGER NOT NULL REFERENCES sources(id),
    requirement_code TEXT NOT NULL,
    purpose_code TEXT,
    channel TEXT NOT NULL CHECK (channel IN ('branch', 'non_face_to_face')),
    visitor_type TEXT NOT NULL CHECK (
        visitor_type IN (
            'account_holder', 'representative', 'agent',
            'representative_or_agent'
        )
    ),
    requirement_level TEXT NOT NULL CHECK (
        requirement_level IN (
            'official_minimum', 'official_required', 'recommended_additional'
        )
    ),
    eligibility_notes TEXT,
    notes TEXT,
    UNIQUE (policy_version_id, requirement_code)
);

ALTER TABLE requirement_sets
    ADD COLUMN IF NOT EXISTS purpose_code TEXT;

CREATE TABLE IF NOT EXISTS documents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_type TEXT NOT NULL UNIQUE,
    label_ko TEXT NOT NULL,
    issuer TEXT,
    issuer_aliases JSONB NOT NULL DEFAULT '[]'::jsonb,
    title_patterns JSONB NOT NULL DEFAULT '[]'::jsonb,
    required_anchors JSONB NOT NULL DEFAULT '[]'::jsonb,
    negative_anchors JSONB NOT NULL DEFAULT '[]'::jsonb,
    doc_number_label TEXT,
    issued_at_labels JSONB NOT NULL DEFAULT '[]'::jsonb,
    validity_days INTEGER CHECK (validity_days IS NULL OR validity_days >= 0),
    acquisition_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_url TEXT,
    as_of DATE NOT NULL,
    last_checked DATE NOT NULL,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS requirement_documents (
    requirement_set_id INTEGER NOT NULL
        REFERENCES requirement_sets(id) ON DELETE CASCADE,
    document_id INTEGER NOT NULL REFERENCES documents(id),
    original_required BOOLEAN,
    issued_within_days INTEGER CHECK (
        issued_within_days IS NULL OR issued_within_days >= 0
    ),
    submission_method TEXT NOT NULL CHECK (
        submission_method IN (
            'original', 'original_or_copy', 'photo_or_pdf',
            'printed_original_photo', 'auto_submit'
        )
    ),
    choice_group TEXT,
    bundle_code TEXT,
    acquisition_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    notes TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CHECK (bundle_code IS NULL OR choice_group IS NOT NULL),
    PRIMARY KEY (requirement_set_id, document_id)
);

CREATE TABLE IF NOT EXISTS preparations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_set_id INTEGER NOT NULL
        REFERENCES requirement_sets(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    name_ko TEXT NOT NULL,
    notes TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    UNIQUE (requirement_set_id, code)
);

CREATE TABLE IF NOT EXISTS policy_conditions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_version_id INTEGER NOT NULL
        REFERENCES policy_versions(id) ON DELETE CASCADE,
    source_id INTEGER NOT NULL REFERENCES sources(id),
    condition_code TEXT NOT NULL,
    channel TEXT NOT NULL CHECK (channel IN ('branch', 'non_face_to_face', 'all')),
    expression_json JSONB NOT NULL,
    result_code TEXT NOT NULL,
    description TEXT NOT NULL,
    UNIQUE (policy_version_id, condition_code)
);

CREATE TABLE IF NOT EXISTS document_field_schema_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL UNIQUE CHECK (version > 0),
    status TEXT NOT NULL DEFAULT 'draft' CHECK (
        status IN ('draft', 'published', 'retired')
    ),
    schema_json JSONB NOT NULL,
    source_filename TEXT,
    source_sha256 TEXT NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at TIMESTAMPTZ,
    CHECK (jsonb_typeof(schema_json) = 'object'),
    CHECK (jsonb_exists(schema_json, 'documents')),
    CHECK (jsonb_exists(schema_json, 'object_schemas'))
);

CREATE INDEX IF NOT EXISTS idx_policy_versions_lookup
    ON policy_versions (bank_id, policy_key, status, version);
CREATE INDEX IF NOT EXISTS idx_policy_operations_lookup
    ON policy_operations (policy_version_id, operation_code);
CREATE INDEX IF NOT EXISTS idx_requirement_sets_lookup
    ON requirement_sets (
        policy_version_id, purpose_code, channel, visitor_type, requirement_level
    );
CREATE INDEX IF NOT EXISTS idx_policy_conditions_lookup
    ON policy_conditions (policy_version_id, channel);
