from __future__ import annotations

import unittest
from pathlib import Path

from modules.policy_db.database import validate_seed_catalog


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = PROJECT_ROOT / "modules" / "policy_db" / "schema.postgresql.sql"


class PostgreSQLPolicyDatabaseTest(unittest.TestCase):
    def test_schema_is_postgresql_only(self) -> None:
        schema = SCHEMA_PATH.read_text(encoding="utf-8")

        self.assertIn("JSONB", schema)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", schema)
        self.assertNotIn("sqlite_master", schema)
        self.assertNotIn("PRAGMA", schema)

    def test_seed_catalog_is_referentially_valid(self) -> None:
        summary = validate_seed_catalog()

        self.assertEqual(summary["seed_files"], 4)
        self.assertEqual(summary["banks"], 6)
        self.assertEqual(summary["policies"], 53)
        self.assertEqual(summary["operations"], 56)
        self.assertEqual(summary["documents"], 50)
        self.assertEqual(summary["requirement_sets"], 66)
        self.assertEqual(summary["document_rules"], 81)

    def test_local_sqlite_artifact_is_not_part_of_runtime(self) -> None:
        self.assertFalse((PROJECT_ROOT / "data" / "proofbridge.db").exists())
        self.assertFalse((PROJECT_ROOT / "modules" / "policy_db" / "schema.sql").exists())


if __name__ == "__main__":
    unittest.main()
