import catalogData from "./catalog.generated.json" with { type: "json" };

// Generated by scripts/extract_policy_catalog.py from the policy database dump.
// Never edit catalog.generated.json by hand; re-run the script instead.

export interface Bank {
  bank_code: string;
  bank_slug: string;
  label_ko: string;
}

export interface Operation {
  operation_id: string;
  operation_code: string;
  label_ko: string;
  bank_code: string;
  bank_slug: string;
  bank_label_ko: string;
  policy_version_id: number;
  policy_key: string;
  policy_label_ko: string;
  customer_type: string;
  account_type: string;
  status: "published" | "draft";
  verified_at: string;
}

export interface RequirementDocument {
  doc_type: string;
  label_ko: string;
  issuer: string | null;
  submission_method: string;
  issued_within_days: number | null;
  validity_days: number | null;
  original_required: boolean | null;
  choice_group: string | null;
  bundle_code: string | null;
  notes: string | null;
  source_url: string | null;
}

export interface RequirementSource {
  publisher: string;
  title: string;
  url: string;
  checked_at: string;
  is_primary: boolean;
}

export interface RequirementSet {
  requirement_code: string;
  purpose_code: string | null;
  channel: string;
  visitor_type: string;
  requirement_level: string;
  eligibility_notes: string | null;
  notes: string | null;
  documents: RequirementDocument[];
  preparations: { code: string; label_ko: string; notes: string | null }[];
  source: RequirementSource;
}

interface Catalog {
  schema_version: string;
  source_file: string;
  generated_on: string;
  banks: Bank[];
  operations: Operation[];
  policies: { policy_version_id: number; requirement_sets: RequirementSet[] }[];
}

const catalog = catalogData as unknown as Catalog;

export const CATALOG_SOURCE = { file: catalog.source_file, generated_on: catalog.generated_on };
export const BANKS: readonly Bank[] = catalog.banks;
export const OPERATIONS: readonly Operation[] = catalog.operations;

const OPERATION_BY_ID = new Map(catalog.operations.map((operation) => [operation.operation_id, operation]));
const SETS_BY_POLICY = new Map(catalog.policies.map((policy) => [policy.policy_version_id, policy.requirement_sets]));

export const OPERATION_IDS: readonly string[] = catalog.operations.map((operation) => operation.operation_id);

export function findOperation(operationId: string): Operation | null {
  return OPERATION_BY_ID.get(operationId) ?? null;
}

export function requirementSetsOf(operation: Operation): readonly RequirementSet[] {
  return SETS_BY_POLICY.get(operation.policy_version_id) ?? [];
}

// The bank name is often repeated inside label_ko ("하나은행 법인계좌 개설").
export function operationLabel(operation: Operation): string {
  const bare = operation.label_ko.startsWith(operation.bank_label_ko)
    ? operation.label_ko.slice(operation.bank_label_ko.length).trim()
    : operation.label_ko;
  return `${operation.bank_label_ko} · ${bare || operation.label_ko}`;
}

// Bank aliases are how people actually write the name; the database stores only
// the official one, so the spoken forms live here next to the catalog.
const EXTRA_ALIASES: Record<string, string[]> = {
  kb: ["국민은행", "국민", "KB", "케이비", "KB은행"],
  kakaobank: ["카뱅", "카카오은행", "kakaobank", "카카오"],
  woori: ["우리뱅크", "woori"],
  hana: ["하나뱅크", "hana", "KEB하나은행", "KEB하나"],
  shinhan: ["신한", "shinhan", "쏠", "SOL"],
  ibk: ["기업은행", "IBK", "중소기업은행"],
};

export const BANK_ALIASES: readonly { bank_slug: string; aliases: string[] }[] = catalog.banks.map((bank) => ({
  bank_slug: bank.bank_slug,
  aliases: [bank.label_ko, bank.bank_slug, ...(EXTRA_ALIASES[bank.bank_slug] ?? [])],
}));
